---
- name: Delete company package
  hosts: all
  tasks:
    - name: Delete Group to RedHat Family
      when: ansible_os_family == "RedHAt"
      group:
        name: "{{ item }}"
        state: absent
      with_items:
        - managers
        - sale
        - marketing
        - IT
        - NOC
        - admins
