---
- name: Install company package
  hosts: all
  tasks:
    - name: Add User to RedHat Family
      when: ansible_os_family == "RedHAt"
      user:
        name: "{{ item }}"
      with_items:
        - bob
        - ben
        - lola
        - lisa
        - brayn
        - oliver
